<?php 
$modulesPath = 'sites/all/modules/ojualproduct/';
include_once($modulesPath. 'inc/function.php');

define('OJUALPRODUCT', 'ojualproduct');
define('OJUALCATEGORY', 'ojualcategory');
define('OJUAL_CATEGORY', 'field_ojual_category');
define('OJUAL_TAXO_DATA', 'ojual_taxo_data'); // change this to follow ojualproduct_taxo_name description

/* ================================================================================
module setting on admin
================================================================================= */
// menu seting user to premium
function ojualproduct_menu() {
	$items = array();
	$items['admin/settings/ojual-product'] = array(
		'title' => 'Ojual Product',
		'description' => 'Ojual Product setting page',
		'page callback' => 'drupal_get_form',
		'page arguments' => array('ojualproduct_admin'),
		'access arguments' => array('administer users'),
		'type' => MENU_NORMAL_ITEM,
	);
	return $items;
}

function ojualproduct_admin() {
	$form = array();

	$form['ojualproduct_node_type'] = array(
		'#type' => 'textfield',
		'#title' => t('Node type for product detail'),
		'#default_value' => variable_get('ojualproduct_node_type', OJUALPRODUCT),
		'#description' => t('Machine name of node type for product detail<br />This node type must have all field for all product category.Below are global field and will use cross category:<br />- product category; dropdown field_ojual_product_category<br />- product type (new or used) radio - field_ojual_product_type<br />- product status (sale/wanted/out of stock/old ads) radio - field_ojual_product_status<br />- product stock (how much is the product) test - field_ojual_product_stock<br />- is free shipping (yes/no) checkbox - field_ojual_free_shipping<br />- is fixed price (yer/no) checkbox - field_ojual_fixed_price<br />- product price; integer with prefix/suffix for currency - field_ojual_product_price<br />- include my footnote (ye/no to include user footnote) checkbox - field_ojual_include_my_footnote'),
		'#required' => TRUE
	);

	$form['ojualproduct_taxo_name'] = array(
		'#type' => 'textfield',
		'#title' => t('Taxonomy for category'),
		'#default_value' => variable_get('ojualproduct_taxo_name', OJUALCATEGORY),
		'#description' => t('Machine of taxonomy name for category<br />In term item description field write each line for the product node information:<br />field machine name | field type | required/optional | rendered type (plain|default) | label position (none, above, left) | tpl (ie: &lt;a href="%s"&gt;link &lt;/a&gt;)<br />example:<br />field_dress_size|text|required|plain|left|%s<br /><b>And set text format as Plain text</b><br />Also don\'t forget the friendly url<br />A bit advise for furl<br />- if parent category not used than: fashion-women-dress.html<br />- if parent catgory in use: fashion/women/dress.html'),
		'#required' => TRUE
	);

	$form['ojualproduct_category_field'] = array(
		'#type' => 'textfield',
		'#title' => t('Category field in product detail'),
		'#default_value' => variable_get('ojualproduct_category_field', OJUAL_CATEGORY),
		'#description' => t('Machine of category field for product detail'),
		'#required' => TRUE
	);


	return system_settings_form($form);
}